quantidade = float(input('Numero de Manifestação Patologias de 1-5: '))
if quantidade == 1:
 patologia = input('Qual a Manifestação Patologia: ')
 print('Avalie de 0 à 5')
 x = float(input('Gravidade: '))
 y = float(input('Urgência: '))
 z = float(input('Tendência: '))
 print('O valor do Grau Crítico',patologia,'é:',x*y*z)
if quantidade == 2:
 patologia1 = input('Qual a 1ª Manifestação Patologia: ')
 print('Avalie de 0 à 5')
 x = float(input('Gravidade: '))
 y = float(input('Urgência: '))
 z = float(input('Tendência: '))
 patologia2 = input('Qual a 2ª Manifestação Patologia: ')
 print('Avalie de 0 à 5')
 x1 = float(input('Gravidade: '))
 y1 = float(input('Urgência: '))
 z1 = float(input('Tendência: '))
 print('O valor do Grau Crítico',patologia1,'é:',x*y*z)
 print('O valor do Grau Crítico' ,patologia2, 'é:',x1*y1*z1) 
 Rank = [patologia1,patologia2]
 Rank.sort(reverse=True)
 print('O Rank de Prioridade é:',Rank)
if quantidade == 3:
  patologia1 = input('Qual a 1ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x = float(input('Gravidade: '))
  y = float(input('Urgência: '))
  z = float(input('Tendência: '))
  patologia2 = input('Qual a 2ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x1 = float(input('Gravidade: '))
  y1 = float(input('Urgência: '))
  z1 = float(input('Tendência: '))
  patologia3 = input('Qual a 3ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x2 = float(input('Gravidade: '))
  y2 = float(input('Urgência: '))
  z2 = float(input('Tendência: '))
  print('O valor do Grau Crítico',patologia1,'é:',x*y*z)
  print('O valor do Grau Crítico' ,patologia2, 'é:',x1*y1*z1)
  print('O valor do Grau Crítico' ,patologia3, 'é:',x2*y2*z2)
  Rank = [patologia1,patologia2,patologia3]
  Rank.sort(reverse=True)
  print('O Rank de Prioridade é:',Rank)
if quantidade == 4:
  patologia1 = input('Qual a 1ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x = float(input('Gravidade: '))
  y = float(input('Urgência: '))
  z = float(input('Tendência: '))
  patologia2 = input('Qual a 2ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x1 = float(input('Gravidade: '))
  y1 = float(input('Urgência: '))
  z1 = float(input('Tendência: '))
  patologia3 = input('Qual a 3ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x2 = float(input('Gravidade: '))
  y2 = float(input('Urgência: '))
  z2 = float(input('Tendência: '))
  patologia4 = input('Qual a Manifestação 4ª Patologia: ')
  print('Avalie de 0 à 5')
  x3 = float(input('Gravidade: '))
  y3 = float(input('Urgência: '))
  z3 = float(input('Tendência: '))
  print('O valor do Grau Crítico',patologia1,'é:',x*y*z)
  print('O valor do Grau Crítico' ,patologia2, 'é:',x1*y1*z1)
  print('O valor do Grau Crítico' ,patologia3, 'é:',x2*y2*z2)
  print('O valor do Grau Crítico' ,patologia4, 'é:',x3*y3*z3)
  Rank = [patologia1,patologia2,patologia3,patologia4]
  Rank.sort(reverse=True)
  print('O Rank de Prioridade é:',Rank)
if quantidade == 5:
  patologia1 = input('Qual a 1ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x = float(input('Gravidade: '))
  y = float(input('Urgência: '))
  z = float(input('Tendência: '))
  patologia2 = input('Qual a 2ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x1 = float(input('Gravidade: '))
  y1 = float(input('Urgência: '))
  z1 = float(input('Tendência: '))
  patologia3 = input('Qual a 3ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x2 = float(input('Gravidade: '))
  y2 = float(input('Urgência: '))
  z2 = float(input('Tendência: '))
  patologia4 = input('Qual a 4ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x3 = float(input('Gravidade: '))
  y3 = float(input('Urgência: '))
  z3 = float(input('Tendência: '))
  patologia5 = input('Qual a 5ª Manifestação Patologia: ')
  print('Avalie de 0 à 5')
  x4 = float(input('Gravidade: '))
  y4 = float(input('Urgência: '))
  z4 = float(input('Tendência: '))
  print('O valor do Grau Crítico',patologia1,'é:',x*y*z)
  print('O valor do Grau Crítico' ,patologia2, 'é:',x1*y1*z1)
  print('O valor do Grau Crítico' ,patologia3, 'é:',x2*y2*z2)
  print('O valor do Grau Crítico' ,patologia4, 'é:',x3*y3*z3)
  print('O valor do Grau Crítico' ,patologia5, 'é:',x4*y4*z4)
  Rank = [patologia1,patologia2,patologia3,patologia4,patologia5]
  Rank.sort(reverse=True)
  print('O Rank de Prioridade é:',Rank)
